### ISSUE TITLE
support an error handler

### ISSUE THREAD

**Issue by oleiba** [kessler/node-dynamic-middleware#3]
Hi! I would love it if the module would also support dynamically switching an error handler middleware, with the signature `function (err, req, res, next)`.

**Comment by kessler** [comment]
@oleiba implemented and published a new major version for npm (4.0.0)

**Comment by oleiba** [comment]
Thanks!
Too bad it breaks support for 0.10-0.12 though.

**Comment by kessler** [comment]
I can make a version for 0.10 - 0.12 no problem

**Comment by oleiba** [comment]
That will be super awesome!

**Comment by kessler** [comment]
not 100% sure how I'll handle the versioning though... need to think about this a little bit. Maybe 4.x.x will be 0.10-0.12 and 5.x.x will be well,  for 5.x.x

Why do you still work with node 0.x?

**Comment by oleiba** [comment]
2 reasons. 
First, Some of our AWS servers are still at 0.12 for various reasons.
Second, I'm developing an open-source infrastructure which I want to keep compatible.

**Comment by kessler** [comment]
As far as I know, there is 99% backward compatibility so it shouldn't be a problem to upgrade and keep the same codebase.

That being said, I don't want to "get into your business" :) so give me a few days and I'll retrofit this module back to be compatible. In the meantime I decided that I will just publish it as another package. Will that work ?

**Comment by oleiba** [comment]
Sure, that can be great :)
